spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/schedual?useUnicode=true&characterEncoding=utf-8"
    username: root
    password: 123456
    jpa:
      database: MYSQL
      generate-ddl: true
      hibernate:
        ddl-auto: none
      show-sql: true
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    #虚拟主机地址
    virtual-host: /
    #连接超时时间
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    #消费端配置
    listener:
      simple:
        #消费端
        concurrency: 5
        #最大消费端数
        max-concurrency: 10
        #自动签收auto  手动 manual
        acknowledge-mode: manual
        #限流（海量数据，同时只能过来一条）
        prefetch: 1
  mail:
    host: smtp.qq.com
    username: 1413537501@qq.com
    password:  oztocpchpwhdjcgj
    properties.mail.smtp.port: 587
    from: 1413537501@qq.com
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: false
    default-encoding: utf-8
server:
  port: 7070