spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8"
    username: root
    password: Wa~!@345
    jpa:
      database: MYSQL
      generate-ddl: true
      hibernate:
        ddl-auto: none
      show-sql: true
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    #虚拟主机地址
    virtual-host: /
    #连接超时时间
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    #消费端配置
    listener:
      simple:
        #消费端
        concurrency: 5
        #最大消费端数
        max-concurrency: 10
        #自动签收auto  手动 manual
        acknowledge-mode: manual
        #限流（海量数据，同时只能过来一条）
        prefetch: 1
server:
  port: 8091